# Generated by Django 3.2.20 on 2023-08-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerclass',
            name='username',
        ),
    ]
