# Generated by Django 3.2.20 on 2023-08-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_woncampaignsclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woncampaignsclass',
            name='customer',
        ),
    ]
