# Generated by Django 3.2.20 on 2023-08-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_woncampaignsclass_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerclass',
            name='social_media',
        ),
    ]
